#!/usr/bin/env bash

set -euo pipefail

d() {
  docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --rm \
    -v "${PWD}:/src" \
    steshaw/nix-docker:3 sh -c 'cd /src && scripts/build'
}

d2() {
  d | tee /dev/stderr | tail -n 1
}

output=$(d2)
image=$(echo "${output}" | cut -d' ' -f3)
docker run "${image}"
